import {React, useEffect, useState} from "react";
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
  const [isImageLoaded, setIsImageLoaded] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setIsImageLoaded(true);
    }, 4000)
  })
  return (
    <div>
      <Head>
        <title>Koris Energy Solutions | Clean Solar</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      {isImageLoaded ? (
        <>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </>
      ) : (
        <div className="flex justify-center items-center bg-black h-screen w-screen gap-4">
          <div className="animate-spin md:w-12 md:h-12 w-8 h-8 border-4 border-r-0 border-t-0 rounded-full"/>
          <h3 className="md:text-4xl md:leading-10 text-lg leading-7 tracking-wider font-bold text-white">Welcome to KORIS<i>energy</i></h3>
        </div>
      )}
    </div>
  );
};

export default Layout;
